import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from 'components/button'
import { Input } from 'components/input'
import Link from 'next/link'

const JobOffer: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Button>tes12312t</Button>
    <Input />
    <Link href="/">back to offers</Link>
  </div>
)

export default JobOffer
