import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from 'components/button'
import { Input } from 'components/input'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Button>tes12312t</Button>
    <Input />
    123123123123
  </div>
)

export default Home
